### ISSUE TITLE
Build fails with Visual Studio 2022

### ISSUE THREAD

**Issue by tokatoka** [googleprojectzero/TinyInst#53]
Hi, thanks for your amazing project.
I am trying to build this with visual studio 2022, but I got the following errors.

```
Run cmake --build . --config Release
Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Building Xed
  ABORT: Library build failed
  [UCRT Version] 10.0.19041.0
  [FOUND MS VERSION] 14
  [PYTHON VERSION] 3.10.0
  ========
  git description stdout:
  fatal: No names found, cannot describe anything.
  ========
  [GIT VERSION] 12.0.1
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/files-xregs.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/via/files-via-padlock.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/amd/files-amd.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/amd/amdxop/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/mpx/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/cet/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/rdrand/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/glm/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/sha/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/xsaveopt/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/xsaves/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/xsavec/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/clflushopt/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/rdseed/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/fsgsbase/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/smap/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/sgx/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/rdpid/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/pt/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/tremont/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/movdir/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/waitpkg/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/cldemote/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/sgx-enclv/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/avx/files.cfg
  [Clearing file list for type dec-spine: [ D:/a/TinyInst/TinyInst/third_party/xed/datafiles/xed-spine.txt ]] 
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/ivbavx/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/hswavx/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/hswbmi/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/hsw/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/bdw/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/skl/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/skx/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/pku/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/clwb/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/clx/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/vnni/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/cpx/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/avx512-bf16/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/knl/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/knm/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/4fmaps-512/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/4vnniw-512/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/vpopcntdq-512/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/avx512f/shared-files.cfg
  [Clearing file list for type dec-spine: [ D:/a/TinyInst/TinyInst/third_party/xed/datafiles/avx/avx-spine.txt ]] 
  CONSIDERING SOURCE D:\a\TinyInst\TinyInst\third_party\xed\datafiles\knc\xed-operand-values-interface-uisa.c source 1
  ADDING SOURCE D:\a\TinyInst\TinyInst\third_party\xed\datafiles\knc\xed-operand-values-interface-uisa.c source 1
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/avx512f/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/avx512cd/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/avx512-skx/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/cnl/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/avx512ifma/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/avx512vbmi/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/icl/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/wbnoinvd/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/pconfig/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/bitalg/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/vbmi2/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/gfni-vaes-vpcl/files-sse.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/gfni-vaes-vpcl/files-avx-avx512.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/vpopcntdq-vl/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/tgl/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/vp2intersect/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/keylocker/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/adl/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/hreset/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/avx-vnni/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/spr/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/uintr/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/amx-spr/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/enqcmd/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/tsx-ldtrk/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/serialize/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/future/files.cfg
  [EXTF PROCESSING] D:/a/TinyInst/TinyInst/third_party/xed/datafiles/tdx/files.cfg
  [EMIT BUILD DEFINES HEADER FILE] 
  R: 1 P: 0 C: 0 E: 0 / 39 msecs [decprep]
  [TOUCH] obj/dummy-prep
  R: 0 P: 0 C: 1 E: 0 / 1 secs 
  	BUILT: D:\a\TinyInst\TinyInst\build\third_party\obj\dummy-prep
  R: 2 P: 0 C: 1 E: 0 / 1 secs [decgen encgen]
  [WRITING] obj/ENC-OUT.txt
  [WRITING] obj/ENC-ERR.txt
  [ENC-GEN] Return code: 0
  R: 1 P: 0 C: 2 E: 0 / 20 secs [decgen]
  	BUILT: D:\a\TinyInst\TinyInst\build\third_party\obj\ENCGEN-OUTPUT-FILES.txt
  [WRITING] obj/DEC-OUT.txt
  [WRITING] obj/DEC-ERR.txt
  [DEC-GEN] Return code: 0
  R: 0 P: 0 C: 3 E: 0 / 25 secs 
  	BUILT: D:\a\TinyInst\TinyInst\build\third_party\obj\DECGEN-OUTPUT-FILES.txt
  R: 4 P: 109 C: 0 E: 0 / 14 msecs 
  [MBUILD WARNING] Command execution failed. Waiting for remaining jobs and exiting.
  R: 3 P: 109 C: 1 E: 1 / 37 msecs 
  [COMMAND     ] "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe" -ID:/a/TinyInst/TinyInst/third_party/xed/include/private -ID:/a/TinyInst/TinyInst/third_party/xed/include/public/xed -ID:/a/TinyInst/TinyInst/third_party/xed/include/public -Iobj -Iobj/include-private     /nologo  /MT  /favor:EM64T  /W4 /WX /wd4091 /wd4127 /wd4505 /wd4702 /wd4244 /wd4292 /DXED_GIT_VERSION="12.0.1" /DXED_AMD_ENABLED /DXED_VIA_ENABLED /DXED_AVX /DXED_SUPPORTS_AVX512 /DXED_MPX /DXED_CET /DXED_SUPPORTS_SHA /DXED_SUPPORTS_WBNOINVD /DXED_DECODER /DXED_ENCODER /DXED_SUPPORTS_LZCNT_TZCNT /DXED_BUILD /c /Foobj/xed-reg-enum.obj D:/a/TinyInst/TinyInst/build/third_party/obj/xed-reg-enum.c
  [EXIT_STATUS ] 399
  [STDERR] 
  
  COMMAND ENCOUNTERD AN EXCEPTION
  Traceback (most recent call last):
    File "D:\a/TinyInst/TinyInst/third_party/xed\..\mbuild\mbuild\util.py", line 1043, in run
      self.sub = subprocess.Popen(cmd_args,
    File "C:\hostedtoolcache\windows\Python\3.10.0\x64\lib\subprocess.py", line 966, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "C:\hostedtoolcache\windows\Python\3.10.0\x64\lib\subprocess.py", line 1435, in _execute_child
      hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
  FileNotFoundError: [WinError 2] The system cannot find the file specified
  
  [MBUILD WARNING] Command execution failed. Waiting for remaining jobs and exiting.
  R: 2 P: 109 C: 2 E: 2 / 38 msecs 
  [COMMAND     ] "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe" -ID:/a/TinyInst/TinyInst/third_party/xed/include/private -ID:/a/TinyInst/TinyInst/third_party/xed/include/public/xed -ID:/a/TinyInst/TinyInst/third_party/xed/include/public -Iobj -Iobj/include-private     /nologo  /MT  /favor:EM64T  /W4 /WX /wd4091 /wd4127 /wd4505 /wd4702 /wd4244 /wd4292 /DXED_GIT_VERSION="12.0.1" /DXED_AMD_ENABLED /DXED_VIA_ENABLED /DXED_AVX /DXED_SUPPORTS_AVX512 /DXED_MPX /DXED_CET /DXED_SUPPORTS_SHA /DXED_SUPPORTS_WBNOINVD /DXED_DECODER /DXED_ENCODER /DXED_SUPPORTS_LZCNT_TZCNT /DXED_BUILD /c /Foobj/xed-address-width-enum.obj D:/a/TinyInst/TinyInst/build/third_party/obj/xed-address-width-enum.c
  [EXIT_STATUS ] 399
  [STDERR] 
  
  COMMAND ENCOUNTERD AN EXCEPTION
  Traceback (most recent call last):
    File "D:\a/TinyInst/TinyInst/third_party/xed\..\mbuild\mbuild\util.py", line 1043, in run
      self.sub = subprocess.Popen(cmd_args,
    File "C:\hostedtoolcache\windows\Python\3.10.0\x64\lib\subprocess.py", line 966, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "C:\hostedtoolcache\windows\Python\3.10.0\x64\lib\subprocess.py", line 1435, in _execute_child
      hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
  FileNotFoundError: [WinError 2] The system cannot find the file specified
  
  [MBUILD WARNING] Command execution failed. Waiting for remaining jobs and exiting.
  R: 1 P: 109 C: 3 E: 3 / 38 msecs 
  [COMMAND     ] "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe" -ID:/a/TinyInst/TinyInst/third_party/xed/include/private -ID:/a/TinyInst/TinyInst/third_party/xed/include/public/xed -ID:/a/TinyInst/TinyInst/third_party/xed/include/public -Iobj -Iobj/include-private     /nologo  /MT  /favor:EM64T  /W4 /WX /wd4091 /wd4127 /wd4505 /wd4702 /wd4244 /wd4292 /DXED_GIT_VERSION="12.0.1" /DXED_AMD_ENABLED /DXED_VIA_ENABLED /DXED_AVX /DXED_SUPPORTS_AVX512 /DXED_MPX /DXED_CET /DXED_SUPPORTS_SHA /DXED_SUPPORTS_WBNOINVD /DXED_DECODER /DXED_ENCODER /DXED_SUPPORTS_LZCNT_TZCNT /DXED_BUILD /c /Foobj/xed-attribute-enum.obj D:/a/TinyInst/TinyInst/build/third_party/obj/xed-attribute-enum.c
  [EXIT_STATUS ] 399
  [STDERR] 
  
  COMMAND ENCOUNTERD AN EXCEPTION
  Traceback (most recent call last):
    File "D:\a/TinyInst/TinyInst/third_party/xed\..\mbuild\mbuild\util.py", line 1043, in run
      self.sub = subprocess.Popen(cmd_args,
    File "C:\hostedtoolcache\windows\Python\3.10.0\x64\lib\subprocess.py", line 966, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "C:\hostedtoolcache\windows\Python\3.10.0\x64\lib\subprocess.py", line 1435, in _execute_child
      hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
  FileNotFoundError: [WinError 2] The system cannot find the file specified
  
  [MBUILD WARNING] Command execution failed. Waiting for remaining jobs and exiting.
  R: 0 P: 109 C: 4 E: 4 / 38 msecs 
  [COMMAND     ] "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe" -ID:/a/TinyInst/TinyInst/third_party/xed/include/private -ID:/a/TinyInst/TinyInst/third_party/xed/include/public/xed -ID:/a/TinyInst/TinyInst/third_party/xed/include/public -Iobj -Iobj/include-private     /nologo  /MT  /favor:EM64T  /W4 /WX /wd4091 /wd4127 /wd4505 /wd4702 /wd4244 /wd4292 /DXED_GIT_VERSION="12.0.1" /DXED_AMD_ENABLED /DXED_VIA_ENABLED /DXED_AVX /DXED_SUPPORTS_AVX512 /DXED_MPX /DXED_CET /DXED_SUPPORTS_SHA /DXED_SUPPORTS_WBNOINVD /DXED_DECODER /DXED_ENCODER /DXED_SUPPORTS_LZCNT_TZCNT /DXED_BUILD /c /Foobj/xed-operand-ctype-enum.obj D:/a/TinyInst/TinyInst/build/third_party/obj/xed-operand-ctype-enum.c
  [EXIT_STATUS ] 399
  [STDERR] 
  
  COMMAND ENCOUNTERD AN EXCEPTION
  Traceback (most recent call last):
    File "D:\a/TinyInst/TinyInst/third_party/xed\..\mbuild\mbuild\util.py", line 1043, in run
      self.sub = subprocess.Popen(cmd_args,
    File "C:\hostedtoolcache\windows\Python\3.10.0\x64\lib\subprocess.py", line 966, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "C:\hostedtoolcache\windows\Python\3.10.0\x64\lib\subprocess.py", line 1435, in _execute_child
      hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
  FileNotFoundError: [WinError 2] The system cannot find the file specified
  
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(242,5): error MSB8066: Custom build for 'D:\a\TinyInst\TinyInst\build\CMakeFiles\86e64b953e1f58fbca11c71e659e096a\xed.lib.rule;D:\a\TinyInst\TinyInst\build\CMakeFiles\5fb1c8601facfde5bcef21843bf1469e\xed.rule;D:\a\TinyInst\TinyInst\third_party\CMakeLists.txt' exited with code 1. [D:\a\TinyInst\TinyInst\build\third_party\xed.vcxproj]
Error: Process completed with exit code 1.
```

It seems to work with vstudio 2019 but not with 2022.
This log was obtained from github ci https://github.com/tokatoka/TinyInst/runs/4403372925
and I can reproduce exactly the same error with vstudio 2022 installed in my local computer.
I'd be glad if you can help me with this.

**Comment by tokatoka** [comment]
OOps, fixing mbuild solved this issue.
