### ISSUE TITLE
Linux: elf compiled with `-no-pie` target not work correctly.

### ISSUE THREAD

**Issue by d0now** [googleprojectzero/TinyInst#68]
### test.sh
```bash
#!/bin/bash

LITECOV=$(realpath $1)

mkdir -p test

echo "- x64 PIE ----"
gcc -o test/pie.x64 test.c
$LITECOV -- test/pie.x64

echo "- x32 PIE ----"
gcc -o test/pie.x32 test.c -m32
$LITECOV -patch_return_addresses -- test/pie.x32

echo "- x64 NO PIE -"
gcc -o test/nopie.x64 test.c -no-pie
$LITECOV -- test/nopie.x64

echo "- x32 NO PIE -"
gcc -o test/nopie.x32 test.c -no-pie -m32
$LITECOV -patch_return_addresses -- test/nopie.x32
```

### test.c
```c
#include <stdio.h>

int main(void) {
    puts("Hello, World!\n");
    return 0;
}
```

### test output (ubuntu 22.04, x64, commit 2c8c5ad9ce4ff49fd6f8346d4d060f874441a267)
```
$ ./test.sh ~/TinyInst/build_x64/litecov
- x64 PIE ----
Hello, World!

Process finished normally
- x32 PIE ----
Hello, World!

Process finished normally
- x64 NO PIE -
[-] PROGRAM ABORT : Error reading target memory         Location : RemoteRead(), /home/lab/TinyInst/src/Linux/debugger.cpp:190

- x32 NO PIE -
[-] PROGRAM ABORT : Error reading target memory         Location : RemoteRead(), /home/lab/TinyInst/src/Linux/debugger.cpp:190

```

### backtrace (gdb)
```
(gdb) r -- test/nopie.x64
Starting program: /home/lab/TinyInst/build_x64/litecov -- test/nopie.x64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff7ff8640 (LWP 436706)]
[Detaching after fork from child process 436707]

Thread 1 "litecov" hit Breakpoint 1, 0x00000000004044a4 in Debugger::RemoteRead(void*, void*, unsigned long) ()
(gdb) bt
#0  0x00000000004044a4 in Debugger::RemoteRead(void*, void*, unsigned long) ()
#1  0x0000000000408f71 in Debugger::GetSegment(unsigned long, unsigned int, unsigned long*) ()
#2  0x0000000000406e1b in Debugger::SetupModules() ()
#3  0x000000000040677e in Debugger::OnEntrypoint() ()
#4  0x000000000041e134 in TinyInst::OnEntrypoint() ()
#5  0x0000000000407a8b in Debugger::HandleDebuggerBreakpoint() ()
#6  0x0000000000409dea in Debugger::HandleStopped(int) ()
#7  0x000000000040a492 in Debugger::DebugLoop(unsigned int) ()
#8  0x000000000040a696 in Debugger::Continue(unsigned int) ()
#9  0x000000000040a9cf in Debugger::Run(int, char**, unsigned int) ()
#10 0x00000000004024a3 in RunTarget(int, char**, unsigned int, unsigned int) ()
#11 0x0000000000402abf in main ()
```

### analysis

https://github.com/googleprojectzero/TinyInst/blob/9970af758207035a1315748821e11356b776eb20/Linux/debugger.cpp#L1627-L1640

as we can see, there are no base address addition to calculate `program_table`.
so if `pie_offset` is `0`,

https://github.com/googleprojectzero/TinyInst/blob/9970af758207035a1315748821e11356b776eb20/Linux/debugger.cpp#L1642-L1646

debugger tries to read invalid address.

**Comment by d0now** [comment]
Oh sorry for PR. can you delete it?

**Comment by ifratric** [comment]
Sorry, looks like we submitted changes at the same time (didn't know you were also working on a fix).

**Comment by d0now** [comment]
It's OK :) thanks for making great project!
